org: juheba
app: collector-app
service: collector-app

frameworkVersion: "3"

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-plugin-tracing
  - serverless-aws-documentation
  - serverless-offline
  - serverless-dynamodb-local

package:
  individually: true

custom:
  webpack:
    concurrency: 10 # desired concurrency, defaults to the number of available cores
  documentation:
    api:
      info:
        version: v.0.0.0
        title: Collector API
        description: Serverless application for collection management
  serverless-offline:
    httpPort: 3003
  dynamodb:
    # Skipping start: DynamoDB Local is not available for stage: dev
    # We need to whitelist the stage, so that dynamodb is started locally.
    start:
      port: 8000
      inMemory: true
      migrate: true
    stages:
      - dev  # whitelist dev-stage
      # ${self:provider.stage}  # whitelists all stages

provider:
  name: aws
  runtime: nodejs18.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, "eu-central-1"}  # "Value is not accepted." ignore this squiggly line. The Serverless IDE Plugins validation feature can't recognise the value.

#  tracing: true
  tracing:
    lambda: true
    apiGateway: true

  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}
    AUTH_0_SECRET_ID: Auth0Secret-${self:provider.stage}
    AUTH_0_SECRET_FIELD: auth0Secret
    COLLECTION_TABLE: ${self:app}-collection-${self:provider.stage}
    COLLECTION_CREATED_AT_INDEX: CollectionCreatedAtIndex
    ITEM_TABLE: ${self:app}-item-${self:provider.stage}
    ITEM_CREATED_AT_INDEX: ItemCreatedAtIndex
    COLLECTION_ITEM_TABLE: ${self:app}-collection-item-${self:provider.stage}
    COLLECTION_ITEM_INDEX: CollectionItemIndex
    LOCATION_TABLE: ${self:app}-location-${self:provider.stage}
    LOCATION_ADDED_AT_INDEX: LocationAddedAtIndex
    TODOS_TABLE: todos-${self:provider.stage}
    TODOS_CREATED_AT_INDEX: CreatedAtIndex
    TODOS_ATTACHMENTS_S3_BUCKET: juheba-todo-attachments-${self:provider.stage}
    ATTACHMENTS_S3_BUCKET: ${self:org}-${self:app}-attachments-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000

  logs:
    # Enable API Gateway logs
    restApi: true

functions:
  - ${file(serverless/functions/auth.yml)}
  - ${file(serverless/functions/collection.yml)}
  - ${file(serverless/functions/item.yml)}
  - ${file(serverless/functions/location.yml)}
#  - ${file(serverless/functions.yml)}

resources: ${file(serverless/ressources.yml)}
