%%{init: {'theme': 'dark'}}%%

classDiagram
    User "1" -- "*" Collection : has
    User "1" -- "*" Lending : lends/borrows
    Collection "*" -- "*" Item : contains
    Item "1" -- "1" Lending : is involved in
    Item "1" -- "1" Location : is located in